name: deploy-mf to S3

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pull-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  actions-repo:
    needs: pull-repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build
      
      - name: Upload build artifacts complete
        uses: actions/upload-artifact@v4
        with:
          name: build complete
          path: dist/

      # - name: Deploy to S3
      #   uses: aws-actions/s3-sync@v2
      #   with:
      #     bucket: ${{ secrets.AWS_S3_BUCKET }}
      #     region: ${{ secrets.AWS_REGION }}
      #     source-dir: dist/pokemon-ngxs
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}